source 'https://rubygems.org'

gem 'activerecord', '~> 5.2.3'
gem 'bootstrap-sass', '~> 3.4', '>= 3.4.1'
gem 'httparty'
gem 'pry'
gem 'rack-flash3'
gem 'rake', '~> 12.3.2'
gem 'require_all', '~> 2.0.0'
gem 'shotgun', '~> 0.9.2'
gem 'sinatra', '~> 2.0.5'
gem 'sinatra-activerecord', '~> 2.0.13'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sqlite3', '~> 1.4.1'
